config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  get 'users/show'

  resources :posts do
    resources :comments, only: :create do       
      patch 'ban', to: 'comments#ban', on: :member      
    end
  end

  root 'posts#index'

  devise_for :users
  get 'users/:id' => 'users#show', as: :user_profile

end

app/models/ckeditor/asset.rb
class Ckeditor::Asset < ActiveRecord::Base
  include Ckeditor::Orm::ActiveRecord::AssetBase
  include Ckeditor::Backend::Paperclip
end

app/models/ckeditor/attachment_file.rb
class Ckeditor::AttachmentFile < Ckeditor::Asset
  has_attached_file :data,
                    :url => "/ckeditor_assets/attachments/:id/:filename",
                    :path => ":rails_root/public/ckeditor_assets/attachments/:id/:filename"

  validates_attachment_presence :data
  validates_attachment_size :data, :less_than => 100.megabytes
  do_not_validate_attachment_file_type :data

  def url_thumb
    @url_thumb ||= Ckeditor::Utils.filethumb(filename)
  end
end

app/models/ckeditor/picture.rb
class Ckeditor::Picture < Ckeditor::Asset
  has_attached_file :data,
                    :url  => "/ckeditor_assets/pictures/:id/:style_:basename.:extension",
                    :path => ":rails_root/public/ckeditor_assets/pictures/:id/:style_:basename.:extension",
                    :styles => { :content => '800>', :thumb => '118x100#' }

  validates_attachment_presence :data
  validates_attachment_size :data, :less_than => 2.megabytes
  validates_attachment_content_type :data, :content_type => /\Aimage/

  def url_content
    url(:content)
  end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post  
  belongs_to :user

  validates :body, presence: true
  
  scope :active, -> { where banned: false }
  scope :recent, -> { order(created_at: :desc).limit 10 }
end

app/models/post.rb
class Post < ActiveRecord::Base
  has_many :comments
  belongs_to :user

  validates :title, presence: true

  scope :recent, -> { order(created_at: :desc).limit 10 }
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :posts
  has_many :comments

  def display_name
    return get_name_from_mail if name.blank?
    name
  end
  
  def recent_activity
    # TODO ??? comments.recent.to_a
    activities = []
    activities.push comments.recent.to_a, posts.recent.to_a
    activities.flatten.sort_by { |activity| activity.created_at }.reverse
  end
  
  private
  def get_name_from_mail
    email.match(/(.*?)@.*/)[1]
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    # devise_parameter_sanitizer.for(:sign_up).push :name, :avatar
    devise_parameter_sanitizer.for(:account_update).push :name, :avatar
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_post
  before_action :check_user, only: :ban
  before_action :verify_captcha, only: :create

  # POST
  def create
    # post = Post.find params[:post_id]
    @comment = @post.comments.build params.require(:comment).permit(:body, :user_id)
    @comment.user = current_user if current_user

    if @comment.save
      flash[:notice] = 'Success'
    else
      flash[:alert]  = 'Fail'
    end
    redirect_to @post
  end

  # PATCH
  def ban  
    comment = @post.comments.find params[:id]
    if comment.update banned: true
      redirect_to @post, notice: 'Success'
    else
      redirect_to @post, alert: 'Fail'
    end
  end

  private
  def set_post
    @post = Post.find params[:post_id]    
  end

  def check_user
    unless current_user == @post.user
      redirect_to @post, alert: 'Only author of the post can ban comments'
    end
  end

  def verify_captcha
    unless current_user
      redirect_to @post, alert: 'go away, bloody robot!' unless verify_recaptcha
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  # before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :authorize_user, only: [:edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all  
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    set_post
  end

  # GET /posts/new
  def new
    @post = current_user.posts.build #Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = current_user.posts.build post_params

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update post_params
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find params[:id]
      # @post = current_user.posts.find_by id: params[:id] # 
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit :title, :content
    end

    def authorize_user
      @post = current_user.posts.find_by id: params[:id]
      redirect_to :back, notice: 'Not authorized' unless @post
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find params[:id]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def user_profile_link user
    link_to user.display_name, user_profile_path(user.id)
  end

  def formatted_date date
    l date, format: :short
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
  def meta_str post
    "#{formatted_date post.created_at} by #{user_profile_link post.user}"
  end

  def last_commenter_name_on comment
    comment.user ? user_profile_link(comment.user) : 'anon'
  end

  def last_comment_meta_str comment
    raw "#{formatted_date comment.created_at} by #{last_commenter_name_on comment}"
  end

  # def comments_meta comments
  #   "Replies: #{comments.count}"
  # end

  def content_preview post    
    preview = truncate(post.content, 
      length: 500, 
      escape: false
      ) { link_to "Continue", post }
    simple_format preview
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def last_seen_tag date, tag=:div ,attributes={}, &block
    if date
      formatted_date = l date, format: :short
      msg = "last seen: #{formatted_date}"
      content_tag tag, msg, attributes, &block
    end
  end

  def avatar_tag user, attributes={size: '25x25', class: 'avatar'}
    avatar_url = if user
      user.avatar || gravatar_url(user.email)
    else
      gravatar_url 'anon'
    end
    image_tag avatar_url, attributes
  end

  def gravatar_url email
    gravatar_id = Digest::MD5::hexdigest(email).downcase
    "http://gravatar.com/avatar/#{gravatar_id}.png"
    # image_tag 'http://placehold.it/260x180'
  end

  def activity_link activity
    activity_path = if activity.is_a? Post
      activity
    else
      "#{post_path activity.post}\##{activity.id}"
    end
    link_to activity.class.to_s, activity_path
  end
end

app/views/comments/_comment.html.haml
%article.comment.panel.panel-default
  %header.panel-heading.meta
    = avatar_tag comment.user    
    = link_to "\##{comment.id}", class: 'comment-bookmark' do
      %span.glyphicon.glyphicon-bookmark(aria-hidden="true")
      = last_comment_meta_str(comment)
    

    - if current_user == comment.post.user
      = link_to ban_post_comment_path(post_id: comment.post.id, id: comment.id), method: :patch, class: 'btn btn-danger btn-xs ban' do
        %span.glyphicon.glyphicon-eye-close(aria-hidden="true")
        ban
       
  .panel-body= sanitize comment.body

app/views/comments/_form.html.haml
= simple_form_for [post, post.comments.build] do |f|
  = f.input :body, required: true, label: false, as: :ckeditor, input_html: { ckeditor: {toolbar: 'simple'} }

  %br
  = recaptcha_tags ajax: true unless current_user
  %br
  = f.submit 'Reply', class: "btn btn-success comment-reply"

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Simple Forum
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags

  %body 
    %nav.navbar.navbar-inverse      
      .container 
        .navbar-header
          = link_to 'Simple Forum', root_path, class: 'navbar-brand'        

        %ul.nav.navbar-nav
          %li
            = link_to new_post_path do
              %span.glyphicon.glyphicon-plus(aria-hidden="true")
              New Post

        %ul.nav.navbar-nav.navbar-right
          - if user_signed_in?
            %li= link_to 'Edit Profile', edit_user_registration_path(current_user)
            %li= link_to 'Sign Out', destroy_user_session_path, method: :delete 
               
          - else
            %li= link_to 'Sign In',  new_user_session_path, class: 'sign-in'
            %li= link_to 'Sign Up',  new_user_registration_path, class: 'sign-up'  
            
    .container    
      .row
        .col-md-8.col-md-push-2
          = render 'shared/notice'
          = yield

    %footer

app/views/posts/_form.html.haml
= simple_form_for @post do |f|
  = f.error_notification

  .form-inputs
    = f.input :title, required: true
    = f.input :content, as: :ckeditor, input_html: { ckeditor: {toolbar: 'mini'} }

  .form-actions
    = f.button :submit

app/views/posts/edit.html.haml
%h1 Editing post

= render 'form'

= link_to 'Show', @post
\|
= link_to 'Back', posts_path

app/views/posts/index.html.haml
- @posts.each do |post|
  %article.post.thumbnail
    %h1= link_to post.title, post
    %p.meta= raw meta_str post
    
    %p= content_preview post
  
    - unless post.comments.empty?
      %p       
        Replies
        %span.badge= post.comments.active.count        
        |
        %span.meta= last_comment_meta_str post.comments.last

= link_to 'New Post', new_post_path, class: "btn btn-success"

app/views/posts/new.html.haml
%h1 New post

= render 'form'

= link_to 'Back', posts_path

app/views/posts/show.html.haml
%article.post
  %header
    %h1= @post.title
      
    %p.meta
      = raw meta_str @post 

    - if current_user == @post.user
      .btn-group
        = link_to edit_post_path(@post), {class: "btn btn-warning btn-xs"} do
          %span.glyphicon.glyphicon-pencil(aria-hidden="true")
          Edit
        = link_to @post, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger btn-xs" do
          %span.glyphicon.glyphicon-remove(aria-hidden="true")
          Destroy

  %p= simple_format @post.content

  %section.comments
    = render @post.comments.active
    = render 'comments/form', post: @post     
    = link_to 'Back to posts', posts_path, class: 'btn back'

app/views/shared/_notice.html.haml
- if notice || alert
  .alert.alert-dismissible{role: 'alert', class: "alert-#{alert ? 'danger' : 'info'}"}
    = notice || alert
    %button.close(type='button' data-dismiss='alert' aria-label='Close')
      %span(aria-hidden='true') &times;

app/views/users/show.html.haml
%h1 #{@user.display_name.capitalize} Profile
= avatar_tag @user, size: '100x100'
.user-stats
  %ul
    %li
      %span.glyphicon.glyphicon-comment(aria-hidden="true") 
      Total posts
      %span.badge= @user.posts.count
    %li
      %span.glyphicon.glyphicon-comment(aria-hidden="true")      
      Total comments
      %span.badge= @user.comments.count
    %li 
      %span.glyphicon.glyphicon-calendar(aria-hidden="true")
      registered: #{formatted_date @user.created_at}
    %li
      %span.glyphicon.glyphicon-calendar(aria-hidden="true")
      = last_seen_tag @user.last_sign_in_at, :span


%h2 Recent activity
- @user.recent_activity.each do |activity|
  %p
    = activity_link activity 
    %span= formatted_date activity.created_at